# Generated by Django 3.0.7 on 2020-07-01 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('owner', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_date')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='last_update_date')),
            ],
        ),
    ]
