# Generated by Django 3.0.7 on 2020-07-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dags',
            new_name='Dag',
        ),
    ]
