# Generated by Django 3.0.7 on 2020-07-01 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dags', '0002_auto_20200701_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dag_id', models.IntegerField()),
                ('task_id1', models.IntegerField()),
                ('task_id2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=20)),
                ('heterogeneous', models.CharField(max_length=20)),
                ('dag_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('status', models.CharField(choices=[(0, '空闲'), (1, '占用')], max_length=2)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_date')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='last_update_date')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=20)),
                ('occupy_time', models.FloatField()),
            ],
        ),
    ]
