# Generated by Django 3.0.7 on 2020-07-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dags', '0004_auto_20200706_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('0', '空闲'), ('1', '占用')], max_length=2),
        ),
    ]
