# Generated by Django 3.0.7 on 2020-07-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dags', '0005_auto_20200706_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dag',
            name='owner',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dag',
            name='room_id',
            field=models.IntegerField(null=True),
        ),
    ]
