# Generated by Django 3.0.7 on 2020-07-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dags', '0006_auto_20200709_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dag',
            name='room_id',
        ),
        migrations.AddField(
            model_name='dag',
            name='dag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
