# Generated by Django 3.0.7 on 2020-07-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dags', '0008_auto_20200709_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dag_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
