# Generated by Django 3.0.7 on 2020-07-14 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dags', '0010_resource_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('dag_id', models.IntegerField(null=True)),
                ('describe', models.CharField(max_length=40, null=True)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_date')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='last_update_date')),
            ],
        ),
    ]
