# Generated by Django 3.0.7 on 2020-07-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dags', '0011_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='dag_id',
        ),
        migrations.AddField(
            model_name='dag',
            name='room_id',
            field=models.IntegerField(null=True),
        ),
    ]
