# Generated by Django 3.0.7 on 2020-07-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dags', '0012_auto_20200714_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('0', '空闲'), ('1', '绑定')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
