# Generated by Django 3.0.7 on 2020-07-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dags', '0013_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dag',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
